spring.application.name=api

spring.datasource.url=jdbc:postgresql://ec2-18-188-6-90.us-east-2.compute.amazonaws.com:5432/nightguard
spring.datasource.username=postgres
spring.datasource.password=vAUIWWTH73HUu101i
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
